### ISSUE TITLE
代码 能运行不?/DNSServer.swift 和DNSServerQuery.swift?

### ISSUE THREAD

**Issue by HTMLtargetblank** [networkextension/Surf_deprecated#1]
@objc 添加了 提出错误 不能编辑通过  求指点

**Comment by CoderJin** [comment]
![image](https://cloud.githubusercontent.com/assets/18577384/18615641/6650c404-7dde-11e6-91c0-0015624c1a0f.png)
这个错误这么解决  ？

**Comment by wuzhongyi1105** [comment]
你运行一下 lipo -info libssl_ub.a 这个命令，目测是 libssl_ub.a 以及上面所有提示 Ignoring file 的文件，都不包含 x86_64 的架构造成的错误
